---
title: "hunger"
author: "issa fall"
date: "March 7, 2016"
output: html_document
---

##hunger dataset
```{r,echo=TRUE}
hunger<-read.csv("http://apps.who.int/gho/athena/data/GHO/WHOSIS_000008.csv? profile= text&filter = COUNTRY::SEX:")

head(hunger)
str(hunger)
summary(hunger)
hunger<-hunger[hunger$SEX != "BTSX", ]
head(hunger)
tail(hunger)
str(hunger)
mean(is.na(hunger))
library(plyr)
library(dplyr)
library(tidyr)
library(ggplot2)
```
##Plot % hungry versus time
```{r,echo=TRUE}
hunger$YEAR<-gsub("_","", hunger$YEAR)

hunger %>%
  select(YEAR, REGION, COUNTRY, SEX, Numeric) %>%
  arrange(YEAR)

lm<-lm(hunger$Numeric ~ hunger$YEAR)
plot(hunger$YEAR, hunger$Numeric, pch =19, col ="blue")
points(hunger$YEAR, hunger$Numeric, pch =19, col =((hunger$SEX == "MLE")*1+1))
```


##Color by male and female
```{r,echo=TRUE}
lmM<-lm(hunger$Numeric[hunger$SEX == "MLE"] ~ hunger$YEAR[hunger$SEX == "MLE"])
lmF<-lm(hunger$Numeric[hunger$SEX == "FMLE"] ~ hunger$YEAR[hunger$SEX == "FMLE"])
plot(hunger$YEAR, hunger$Numeric, pch =19)
points(hunger$YEAR, hunger$Numeric, pch =19,col =((hunger$SEX =="MLE")*1+1))
lines(hunger$YEAR[hunger$SEX == "MLE"], lmM$fitted, col ="black",lwd =3)
lines(hunger$YEAR[hunger$SEX == "FMLE"], lmF$fitted, col ="red", lwd =3)
```

##Two lines,same slope in R
```{r,echo=TRUE}
lmBoth<-lm(hunger$Numeric ~ hunger$YEAR + hunger$SEX)
plot(hunger$YEAR, hunger$Numeric,pch =19)
points(hunger$YEAR, hunger$Numeric, pch =19, col =((hunger$SEX == "MLE")*1+1))
abline(c(lmBoth$coeff[1], lmBoth$coeff[2]),col ="red", lwd =3)
abline(c(lmBoth$coeff[1] + lmBoth$coeff[3], lmBoth$coeff[2]), col ="black", lwd =3)
```

##Two lines different slopes(interactions)
```{r,echo=TRUE}
lmBoth<-lm(hunger$Numeric ~ hunger$YEAR + hunger$SEX + hunger$SEX *  hunger$YEAR)
plot(hunger$YEAR , hunger$Numeric, pch =19)
points(hunger$YEAR, hunger$Numeric, pch =19, col = ((hunger$SEX =="MLE")*1+1))
abline(c(lmBoth$coeff[1], lmBoth$coeff[2]), col ="red", lwd =3)
abline(c(lmBoth$coeff[1] + lmBoth$coeff[3], lmBoth$coeff[2] + lmBoth$coeff[4]), col ="black", lwd =3)
```

##Summary(lmBoth)
```{r,echo=TRUE}
summary(lmBoth)
```
##Let's find out some information
```{r,echo=TRUE}

ddply(hunger, "REGION", function(x) c(count =nrow(x),
                                      mean = mean(x$Numeric),
                                      median = median(x$Numeric)))
africa<-hunger[hunger$REGION == "AFR", ]
head(africa)
ddply(africa, "COUNTRY", function(x) c(count = nrow(x),
                                   mean = mean(x$Numeric),
                                   median = median(x$Numeric)))
sen<-hunger[hunger$COUNTRY == "SEN", ]
summary(sen)
```
##Let's have some information about senegal
```{r,echo=TRUE}
africa %>%
  select(YEAR ,REGION, COUNTRY , SEX, Numeric) %>%
  arrange(YEAR) %>%
  filter(COUNTRY == "SEN", SEX == "FMLE")


library(dygraphs)
africa %>%
  select(YEAR, SEX, Numeric) %>%
  filter(YEAR == 2005:2011, SEX == "FMLE")

##dygraph(africa, main ="Female hunger") 
##  dyRangeSelector()
```
  



     


