---
title: "MTCARS_report"
author: "ISSA FALL"
date: "Friday, June 05, 2015"
output: html_document
---
After using regression models and exploratory analysis,I found that manual is more efficient 
than automatic in terms of mpg by the amount of 7.24494 mpg.
And automatic is more powerful than manual by the amount of 33.4168 hp.
In this case, I think it's a matter of choice between efficiency and power here.
Let's calculate the difference in mpg between automatic(0) and manual(1).
```{r,echo=TRUE}
library(datasets)
data(mtcars)
head(mtcars)
str(mtcars)
lm(mpg~., mtcars)
## automatic(0) and manual(1)
table(mtcars$am)
## Let's calculate the mean in mpg for each manual(1) and automatic(0)
tapply(mtcars$mpg,mtcars$am,mean,simplify =FALSE)
## The difference in means equals
24.39231 - 17.14737
## Let's look the difference in terms of power (hp): automatic(0) and manual(1)
tapply(mtcars$hp,mtcars$am,mean,simplify =FALSE)
160.2632 - 126.8464
fit<-lm(mpg~am,mtcars)
fit
```
APPENDIX
```{r,echo=TRUE}
boxplot(mpg~am, col="red",xlab="am",ylab="mpg",col.axis="blue",col.lab="red",data=mtcars)
## DIAGNOSTICS OF RESIDUALS
plot(fit,which =1)
plot(fit, which =2)
plot(fit, which =3)
## Now,let's plot automatic(0) and manual(1) to compare their power
library(ggplot2)
qplot(hp,mpg,data=mtcars,facets=.~am)
qplot(hp,mpg,data=mtcars,color=am)
qplot(am,mpg,data=mtcars,geom=c("point","smooth"))
```

